config-version: 2
dev: false
#.. _____________________ ..#
## -- // WARNING \\ -- 
## -- THIS WORK IS UNDER EXCLUSIVE COPRIGHT FOR BAITCORP LABS. DISTRIBUTION, MODIFICATION, SELLING, OR SHARING THIS WITHOUT EXPLICIT PERMISSION FROM BAITCORP LABS IS STRICTLY PROHIBITED.
## -- LICENSED FOR MODIFICATION TO AND ONLY TO: "BAITCORP LABS" [FR], "CCHOST PARIS" [FR].
## -- THIS PROGRAM IS FREE. BY DOWNLOADING THIS YOU AGREE NOT TO SHARE OR MODIFY IT WITHOUT A LICENSE.
## -- 
## -- DupePlugin Sebastian Giheta 2019-2020
#.. _____________________ ..#

#  ________                         __________ .__                  .__         
#  \______ \   __ __ ______    ____ \______   \|  |   __ __   ____  |__|  ____  
#   |    |  \ |  |  \\____ \ _/ __ \ |     ___/|  |  |  |  \ / ___\ |  | /    \ 
#   |    `   \|  |  /|  |_> >\  ___/ |    |    |  |__|  |  // /_/  >|  ||   |  \
#  /_______  /|____/ |   __/  \___  >|____|    |____/|____/ \___  / |__||___|  /
#          \/        |__|         \/                       /_____/           \/ 
# DupePlugin by Sebastian Giheta, owner of 8b8t.xyz
#.. _____________________ ..#


# log duping to the console
log: true
# for log-color you can use numbers 0-9 and letters a-f
log-color: a
# log shulker contents (might be a bit spammy for large servers)
log-shulkers: true

# Random duped item amount. set this to the same number to always dupe the same amount. limited-items will override this.
# max random dupe amount (max 128)
max: 65
# minimum dupe amount
min: 62

# Items which are limited by a max stack size
#   - use the materials listed at <> https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html <>
#   - totem and totem_of_undying are added because of it's material name change in 1.13 (use "totem" for any version <1.13)
limited-items:
 - TOTEM
 - TOTEM_OF_UNDYING
 - DRAGON_EGG
maxstacksize: 48

#disable duping shulkers
disable-shulkers: false

# check when duping a shulker box? this will also check for items that are incorrectly stacked
illegal-check-shulkers: true
# items that will not be duped
illegal-items:
 - BEDROCK
 - SPAWN_EGG
# mode
# 1: remove the item
# 2: cancel the duping but dont remove
illegaldupemode: 1